from typing import List, Literal, TypedDict


class AgentState(TypedDict):
    """
    Represents the state of the agent in the LangGraph graph.

    Attributes:
        input (str): The user's input query.
        chat_history (List[str]): A list of past chat messages.
        intermediate_steps (List[str]): A list of steps taken by the agent.
        tool_output (str): The output from any tool calls made by the agent.
        response (str): The final response generated by the agent.
    """

    input: str
    chat_history: List[str]
    intermediate_steps: List[str]
    tool_output: str
    response: str
